#!/usr/bin/env bash
cd ~/_installed/CloudScraper
source ~/_installed/CloudScraper/CloudScraper-venv/bin/activate
~/_installed/CloudScraper/CloudScraper-venv/bin/python3 /home/sherlock/Programs/CloudScraper/CloudScraper.py "$@"
