#!/usr/bin/env bash
cd $MY_SHERLOCK/CloudScraper
source $MY_SHERLOCK/CloudScraper/CloudScraper-venv/bin/activate
$MY_SHERLOCK/CloudScraper/CloudScraper-venv/bin/python3 $MY_SHERLOCK/CloudScraper/CloudScraper.py "$@"
