#!/usr/bin/env bash
cd /opt/sherlock/CloudScraper
source /opt/sherlock/CloudScraper/CloudScraper-venv/bin/activate
/opt/sherlock/CloudScraper/CloudScraper-venv/bin/python3 /opt/sherlock/CloudScraper/CloudScraper.py "$@"
