#!/usr/bin/env bash
cd ~/_installed/DNSRecon
source ~/_installed/DNSRecon/DNSRecon-venv/bin/activate
sudo ~/_installed/DNSRecon/DNSRecon-venv/bin/python3 /home/sherlock/Programs/DNSRecon/dnsrecon.py "$@"
