#!/usr/bin/env bash
cd ~/_installed/Hostintel
source ~/_installed/Hostintel/Hostintel-venv/bin/activate
~/_installed/Hostintel/Hostintel-venv/bin/python3 /home/sherlock/Programs/Hostintel/hostintel.py "$@"
