#!/usr/bin/env bash
cd ~/_installed/metagoofil
source ~/_installed/metagoofil/metagoofil-venv/bin/activate
~/_installed/metagoofil/metagoofil-venv/bin/python3 /home/sherlock/Programs/metagoofil/metagoofil.py "$@"
