#!/usr/bin/env bash
cd $MY_SHERLOCK/metagoofil
source $MY_SHERLOCK/metagoofil/metagoofil-venv/bin/activate
$MY_SHERLOCK/metagoofil/metagoofil-venv/bin/python3 $MY_SHERLOCK/metagoofil/metagoofil.py "$@"
