#!/usr/bin/env bash
cd ~/_installed/protosint
source ~/_installed/protosint/protosint-venv/bin/activate
~/_installed/protosint/protosint-venv/bin/python3 /home/sherlock/Programs/protosint/protosint.py
