#!/usr/bin/env bash
cd ~/_installed/Sherlock
source ~/_installed/Sherlock/Sherlock-venv/bin/activate
~/_installed/Sherlock/Sherlock-venv/bin/python3 /home/sherlock/Programs/Sherlock/sherlock/sherlock.py "$@"
