#!/usr/bin/env bash
cd $MY_SHERLOCK/Sherlock
source $MY_SHERLOCK/Sherlock/Sherlock-venv/bin/activate
$MY_SHERLOCK/Sherlock/Sherlock-venv/bin/python3 $MY_SHERLOCK/Sherlock/sherlock/sherlock.py "$@"
#need to look at what this does post install.  
